// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Theo_EnemyHPGauge","status":true,"description":"v1.0.1 - Theo Enemy HP Gauge | Visual HP gauge for the enemies","parameters":{"option":"","pos":"Bottom","defeat":"false","alwaysShown":"false","prop":"","width":"100","height":"11","animeDur":"45","displayDur":"25","border":"2","segments":"1","gaugecolor":"","lcolorindex":"20","rcolorindex":"21","bcolorindex":"15","aftImage":"18","aftAlpha":"200"}},
{"name":"Galv_ImageCache","status":true,"description":"(v.1.1) Pre-cache images that cause issues when loading during gameplay","parameters":{"Folder 1":"animations|","Folder 2":"faces|","Folder 3":"sv_actors|","Folder 4":"tilesets|","Folder 5":"","Folder 6":"","Folder 7":"","Folder 8":"","Folder 9":"","Folder 10":"","Folder 11":"","Folder 12":"","Folder 13":"","Folder 14":"","Folder 15":"","Folder 16":"","Folder 17":"","Folder 18":"","Folder 19":"","Folder 20":"","Folder 21":"","Folder 22":"","Folder 23":"","Folder 24":"","Folder 25":""}}
];
